app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/about.html.twig
    
contact:
    path: /contact
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/contact.html.twig

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    
_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin
    
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile
    
sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting
    
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
    
# sonata front controller
sonata_customer:
    resource: "@SonataCustomerBundle/Resources/config/routing/customer.xml"
    prefix: /shop/user

sonata_basket:
    resource: "@SonataBasketBundle/Resources/config/routing/basket.xml"
    prefix: /shop/basket

sonata_order:
    resource: "@SonataOrderBundle/Resources/config/routing/order.xml"
    prefix: /shop/user/invoice

sonata_product_catalog:
    resource: "@SonataProductBundle/Resources/config/routing/catalog.xml"
    prefix: /shop/catalog

sonata_product:
    resource: "@SonataProductBundle/Resources/config/routing/product.xml"
    prefix: /shop/product

sonata_payment:
    resource: "@SonataPaymentBundle/Resources/config/routing/payment.xml"
    prefix: /shop/payment

sonata_invoice:
    resource: "@SonataInvoiceBundle/Resources/config/routing/invoice.xml"
    prefix: /shop/user/invoice
    
news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news