<?php

/*
 * This file is part of the sonata project.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\ProductBundle\Provider;

use Sonata\ProductBundle\Model\BaseProductProvider;
use Sonata\AdminBundle\Form\FormMapper;

/**
 * This file has been generated by the EasyExtends bundle ( https://sonata-project.org/easy-extends )
 *
 * References :
 *   custom repository : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en#querying:custom-repositories
 *   query builder     : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/query-builder/en
 *   dql               : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/dql-doctrine-query-language/en
 *
 * @author <yourname> <youremail>
 */
class CatalogProductProvider extends BaseProductProvider {

    /**
     * {@inheritDoc}
     */
    public function getBaseControllerName() {
        return 'SonataProductBundle:Catalog';
    }

    /**
     * {@inheritdoc}
     */
    public function buildEditForm(FormMapper $formMapper, $isVariation = false) {
        $formMapper->with('Product', array(
            'class' => 'col-md-9',
        ));

        $formMapper->add('enabled');

        $formMapper->add('shop', null, array('required' => true,
            'placeholder' => 'Choose shop',
            'error_mapping' => array(
                '.' => 'shop',
        )));

        $formMapper->add('name');
        $formMapper->add('sku');

        if (!$isVariation || in_array('description', $this->variationFields)) {
            $formMapper->add('description', 'sonata_formatter_type', array(
                'source_field' => 'rawDescription',
                'source_field_options' => array('attr' => array('class' => 'span10', 'rows' => 20)),
                'format_field' => 'descriptionFormatter',
                'target_field' => 'description',
                'event_dispatcher' => $formMapper->getFormBuilder()->getEventDispatcher(),
            ));
        }

        if (!$isVariation || in_array('short_description', $this->variationFields)) {
            $formMapper->add('shortDescription', 'sonata_formatter_type', array(
                'source_field' => 'rawShortDescription',
                'source_field_options' => array('attr' => array('class' => 'span10', 'rows' => 20)),
                'format_field' => 'shortDescriptionFormatter',
                'target_field' => 'shortDescription',
                'event_dispatcher' => $formMapper->getFormBuilder()->getEventDispatcher(),
            ));
        }

        $formMapper->end();

        $formMapper
                ->with('Price', array(
                    'class' => 'col-md-3',
                ))
                ->add('price', 'number', array('required' => false))
                ->add('priceIncludingVat')
                ->add('vatRate', 'number', array('required' => false))
                ->add('stock', 'integer', array('required' => false))
                ->end();
        ;

        if (!$isVariation || in_array('image', $this->variationFields) || in_array('gallery', $this->variationFields)) {
            $formMapper->with('Media', array(
                'class' => 'col-md-3',
            ));

            if (!$isVariation || in_array('image', $this->variationFields)) {
                $formMapper->add('image', 'sonata_type_model_list', array(
                    'required' => false,
                        ), array(
                    'link_parameters' => array(
                        'context' => 'product_catalog',
                        'filter' => array('context' => array('value' => 'product_catalog')),
                        'provider' => '',
                    ),
                ));
            }

//            if (!$isVariation || in_array('gallery', $this->variationFields)) {
//                $formMapper->add('gallery', 'sonata_type_model_list', array(
//                    'required' => false,
//                        ), array(
//                    'link_parameters' => array(
//                        'context' => 'product_catalog',
//                        'filter' => array('context' => array('value' => 'product_catalog')),
//                        'provider' => '',
//                    ),
//                ));
//            }

            $formMapper->end();
        }
    }

}
