<?php

/*
 * This file is part of the sonata project.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\ProductBundle\Provider;

use Sonata\ProductBundle\Model\BaseProductProvider;
use Sonata\AdminBundle\Form\FormMapper;
use Symfony\Component\Security\Core\SecurityContextInterface;

/**
 * This file has been generated by the EasyExtends bundle ( https://sonata-project.org/easy-extends )
 *
 * References :
 *   custom repository : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en#querying:custom-repositories
 *   query builder     : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/query-builder/en
 *   dql               : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/dql-doctrine-query-language/en
 *
 * @author <yourname> <youremail>
 */
class OfferProductProvider extends BaseProductProvider {

    /**
     * Security Context
     * @var \Symfony\Component\Security\Core\SecurityContextInterface
     */
    protected $securityContext = null;

    /**
     * {@inheritdoc}
     */
    public function setSecurityContext(SecurityContextInterface $securityContext) {
        $this->securityContext = $securityContext;
    }

    /**
     * {@inheritdoc}
     */
    public function getSecurityContext() {
        return $this->securityContext;
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseControllerName() {
        return 'SonataProductBundle:Offer';
    }

    /**
     * {@inheritdoc}
     */
    public function buildEditForm(FormMapper $formMapper, $isVariation = false) {
        $formMapper->with('Product', array(
            'class' => 'col-md-9',
        ));

        $formMapper->add('enabled');

        if ($this->securityContext->isGranted('ROLE_ADMIN')) {
            $formMapper->add('shop', 'sonata_type_model_list', array(
                'required' => true
            ));
        } else {
            $formMapper->add('shop', 'sonata_type_model_hidden');
        }

        $formMapper->add('name');
        $formMapper->add('sku');

        if (!$isVariation || in_array('description', $this->variationFields)) {
            $formMapper->add('description', 'sonata_formatter_type', array(
                'source_field' => 'rawDescription',
                'source_field_options' => array('attr' => array('class' => 'span10', 'rows' => 20)),
                'format_field' => 'descriptionFormatter',
                'target_field' => 'description',
                'event_dispatcher' => $formMapper->getFormBuilder()->getEventDispatcher(),
            ));
        }

        if (!$isVariation || in_array('short_description', $this->variationFields)) {
            $formMapper->add('shortDescription', 'sonata_formatter_type', array(
                'source_field' => 'rawShortDescription',
                'source_field_options' => array('attr' => array('class' => 'span10', 'rows' => 20)),
                'format_field' => 'shortDescriptionFormatter',
                'target_field' => 'shortDescription',
                'event_dispatcher' => $formMapper->getFormBuilder()->getEventDispatcher(),
            ));
        }

        $formMapper->end();

        $formMapper
                ->with('Price', array(
                    'class' => 'col-md-3',
                ))
                ->add('price', 'number', array('required' => true))
                ->add('priceIncludingVat')
                ->add('vatRate', 'number', array('required' => true))
                ->add('stock', 'integer', array('required' => false))
                ->end();
        ;

        if (!$isVariation || in_array('image', $this->variationFields) || in_array('gallery', $this->variationFields)) {
            $formMapper->with('Media', array(
                'class' => 'col-md-3',
            ));

            if (!$isVariation || in_array('image', $this->variationFields)) {
                $formMapper->add('image', 'sonata_type_model_list', array(
                    'required' => false,
                        ), array(
                    'link_parameters' => array(
                        'context' => 'product_offer',
                        'filter' => array('context' => array('value' => 'product_offer')),
                        'provider' => '',
                    ),
                ));
            }

//            if (!$isVariation || in_array('gallery', $this->variationFields)) {
//                $formMapper->add('gallery', 'sonata_type_model_list', array(
//                    'required' => false,
//                        ), array(
//                    'link_parameters' => array(
//                        'context' => 'product_offer',
//                        'filter' => array('context' => array('value' => 'product_offer')),
//                        'provider' => '',
//                    ),
//                ));
//            }

            $formMapper->end();
        }
    }

}
