# Doctrine Configuration
doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
            currency: Sonata\Component\Currency\CurrencyDoctrineType
            
sonata_delivery:
    services:
        free_address_required:
            name: Free
#            enabled: true
            priority: 1
            code: free

    selector: sonata.delivery.selector.default

sonata_payment:
    services:
        pass:
            name:    Pass
#            enabled: true
            code:    pass
            browser: sonata.payment.browser.curl

            transformers:
                basket: sonata.payment.transformer.basket
                order:  sonata.payment.transformer.order

            options:
                shop_secret_key: assdsds
                url_callback:    sonata_payment_callback
                url_return_ko:   sonata_payment_error
                url_return_ok:   sonata_payment_confirmation

    # service which find the correct payment methods for a basket
    selector: sonata.payment.selector.simple

    # service which generate the correct order and invoice number
    generator: sonata.payment.generator.mysql

    transformers:
        order:  sonata.payment.transformer.order
        basket: sonata.payment.transformer.basket

sonata_price:
    currency: EUR

sonata_product:
    products:
        app.product.catalog:
            provider:             app.product.catalog.type  # Required
            manager:              app.product.catalog.manager  # Required
            variations:
                fields:           [] # Required