services:
    app.product.catalog.manager:
        class: Sonata\ProductBundle\Entity\ProductManager
        arguments: [ Application\Sonata\ProductBundle\Entity\Catalog, '@doctrine' ]

    app.product.catalog.type:
        class: Application\Sonata\ProductBundle\Provider\CatalogProductProvider
        arguments: [ '@serializer' ]
        
    app.admin.shop:
        class: AppBundle\Admin\ShopAdmin
        arguments: [~, AppBundle\Entity\Shop, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Shop }